# Generated by Django 3.1.5 on 2021-02-16 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DecoctCenter',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False, verbose_name='煎煮中心编号')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='煎煮中心名称')),
                ('note', models.CharField(default='', max_length=50, verbose_name='备注')),
                ('register_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('province', models.CharField(max_length=10, verbose_name='煎煮中心所在省份')),
                ('city', models.CharField(max_length=10, verbose_name='煎煮中心所在城市')),
                ('zone', models.CharField(max_length=10, verbose_name='煎煮中心所在区县')),
                ('address', models.CharField(max_length=200, verbose_name='煎煮中心详细地址')),
                ('status', models.SmallIntegerField(default=1, verbose_name='是否停用')),
            ],
            options={
                'verbose_name': '煎煮中心信息表',
                'verbose_name_plural': '煎煮中心信息表',
                'db_table': 'tb_decoct_center',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_code', models.CharField(max_length=10, unique=True, verbose_name='商品编码')),
                ('goods_name', models.CharField(max_length=50, verbose_name='商品名称')),
                ('short_code', models.CharField(max_length=50, verbose_name='简码(商品名称首字母大写)')),
                ('english_name', models.CharField(max_length=100, verbose_name='英文名称')),
                ('chinese_name', models.CharField(max_length=100, verbose_name='中文名称')),
                ('price', models.DecimalField(decimal_places=5, default=0, max_digits=10, verbose_name='价格')),
                ('stock', models.IntegerField(default=0, verbose_name='库存')),
                ('unit', models.CharField(default='g', max_length=5, verbose_name='单位')),
                ('status', models.IntegerField(default=1, verbose_name='是否停用')),
                ('alias1', models.CharField(max_length=20, verbose_name='别名1')),
                ('alias2', models.CharField(max_length=20, verbose_name='别名2')),
                ('alias3', models.CharField(max_length=20, verbose_name='别名3')),
                ('alias4', models.CharField(max_length=20, verbose_name='别名4')),
                ('alias5', models.CharField(max_length=20, verbose_name='别名5')),
                ('alias6', models.CharField(max_length=20, verbose_name='别名6')),
                ('alias7', models.CharField(max_length=20, verbose_name='别名7')),
                ('alias8', models.CharField(max_length=20, verbose_name='别名8')),
                ('alias9', models.CharField(max_length=20, verbose_name='别名9')),
                ('alias10', models.CharField(max_length=20, verbose_name='别名10')),
                ('goods_norms', models.CharField(max_length=100, null=True, verbose_name='商品规格')),
                ('goods_orgin', models.CharField(max_length=100, null=True, verbose_name='商品产地')),
                ('goods_type', models.SmallIntegerField(default='0', verbose_name='商品(药材)类型:0 中药，1 西药')),
                ('oper_id', models.IntegerField(null=True, verbose_name='主要记录修改者，方便追溯')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='数据更新时间')),
            ],
            options={
                'verbose_name': '商品信息表',
                'verbose_name_plural': '商品信息表',
                'db_table': 'tb_goods',
            },
        ),
        migrations.CreateModel(
            name='GoodsDetails',
            fields=[
                ('goods_code', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='商品编码')),
                ('goods_name', models.CharField(max_length=50, verbose_name='商品名称')),
                ('property', models.CharField(max_length=100, verbose_name='性味')),
                ('channels', models.CharField(max_length=100, verbose_name='归经')),
                ('actions', models.TextField(verbose_name='功效作用')),
                ('usage_dosage', models.TextField(verbose_name='用法用量')),
                ('precaution', models.CharField(max_length=200, verbose_name='禁忌')),
            ],
            options={
                'verbose_name': '商品详情表',
                'verbose_name_plural': '商品详情表',
                'db_table': 'tb_goodsDetails',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, unique=True, verbose_name='菜单名称')),
                ('icon', models.CharField(blank=True, max_length=100, null=True, verbose_name='菜单图标')),
                ('menu_type', models.CharField(max_length=10, verbose_name='菜单类型')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.menu')),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单',
                'db_table': 'tb_menu',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, unique=True, verbose_name='权限')),
                ('url', models.CharField(max_length=128)),
                ('per_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='选项卡id')),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.menu')),
            ],
            options={
                'verbose_name': '权限',
                'verbose_name_plural': '权限',
                'db_table': 'tb_authority',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=50, unique=True, verbose_name='角色名称')),
                ('permissions', models.ManyToManyField(to='management.Permission')),
            ],
            options={
                'verbose_name': '角色信息表',
                'verbose_name_plural': '角色信息表',
                'db_table': 'tb_role',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='用户名')),
                ('work_num', models.CharField(max_length=50, null=True, unique=True, verbose_name='工号')),
                ('name', models.CharField(max_length=50, null=True, unique=True, verbose_name='姓名')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('email', models.CharField(max_length=100, verbose_name='电子邮箱')),
                ('nickname', models.CharField(max_length=100, verbose_name='昵称')),
                ('department', models.CharField(max_length=100, verbose_name='部门')),
                ('register_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('login_time', models.DateTimeField(null=True, verbose_name='最近登录时间')),
                ('rank', models.IntegerField(default=0, verbose_name='管理员级别')),
                ('is_disabled', models.IntegerField(default=1, verbose_name='是否禁用')),
                ('rights', models.CharField(max_length=100, verbose_name='权限')),
                ('role', models.ManyToManyField(to='management.Role')),
            ],
            options={
                'verbose_name': '用户信息表',
                'verbose_name_plural': '用户信息表',
                'db_table': 'tb_admin',
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('company_num', models.AutoField(primary_key=True, serialize=False, verbose_name='机构编号')),
                ('company_name', models.CharField(max_length=32, unique=True, verbose_name='机构名称')),
                ('register_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('status', models.SmallIntegerField(default=1, verbose_name='是否停用')),
                ('company_pass', models.CharField(max_length=50, verbose_name='密码')),
                ('company_type', models.IntegerField(default=0, verbose_name='公司类型  0 医院管理系统, 1 医院his, 2 其他')),
                ('is_doc_outh', models.IntegerField(default=0, verbose_name='提供给第三方移动网络平台医生认证 0 不需要，1 需要')),
                ('is_send_msg', models.IntegerField(default=0, verbose_name='0发短信,1不发短信')),
                ('salesman', models.CharField(max_length=20, verbose_name='业务员')),
                ('sales_tel', models.CharField(max_length=20, verbose_name='业务员电话')),
                ('his_abutment', models.CharField(max_length=20, verbose_name='医院对接人')),
                ('his_abutment_tel', models.CharField(max_length=20, verbose_name='医院对接人电话')),
                ('his_grade', models.CharField(max_length=50, verbose_name='医院的分类比如三甲医院、二甲医院、社区医院')),
                ('his_addr', models.CharField(max_length=255, verbose_name='医院地址')),
                ('business_practice_name', models.CharField(max_length=1000, verbose_name='营业执照')),
                ('medical_licensing_license_name', models.CharField(max_length=1000, verbose_name='医疗机构执业许可证')),
                ('distribution_description', models.CharField(max_length=255, verbose_name='配送时段描述')),
                ('default_consignee', models.CharField(max_length=255, verbose_name='默认收货人')),
                ('default_tel', models.CharField(max_length=255, verbose_name='默认收货人电话')),
                ('defalut_addr', models.CharField(max_length=255, verbose_name='默认收货地址')),
                ('defalut_djdj', models.FloatField(default=1.5, verbose_name='默认代煎价格')),
                ('isOnline', models.IntegerField(default=0, verbose_name='对接完成:0是未上线，1是已上线(目前数据不准确,需要实时更新)')),
                ('short_name', models.CharField(max_length=255, verbose_name='简称')),
                ('platform_type', models.IntegerField(default=0, verbose_name='订单煎煮中心分配规则:0 默认 ,1 按医疗机构 ,2 按地址')),
                ('ascription', models.IntegerField(default=0, verbose_name='机构所属分类 0 医院, 1 企业单位')),
                ('oper_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.user', verbose_name='主要记录修改者id,方便追溯')),
                ('storage_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.decoctcenter', verbose_name='煎煮中心')),
            ],
            options={
                'verbose_name': '医疗机构信息',
                'verbose_name_plural': '医疗机构信息',
                'db_table': 'tb_off_oper',
            },
        ),
    ]
